apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: msaez-dev
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: msaez-dev
    spec:
      containers:
        - name: msaez-dev
          image: gcr.io/$PROJECT_ID/eventstorming-ui-dev:$COMMIT_SHA
          ports:
            - containerPort: 8080
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: msaez-dev-vsvc        # required
            routes:
            - primary                 # required
          destinationRule:
            name: msaez-dev-destrule    # required
            canarySubsetName: canary  # required
            stableSubsetName: stable  # required
      steps:
      - setWeight: 5
      - pause:
          duration: 10s
      - setWeight: 20
      - pause:
          duration: 10s
      - setWeight: 40
      - pause:
          duration: 10s
      - setWeight: 60
      - pause:
          duration: 10s
      - setWeight: 80
      - pause:
          duration: 10s
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: msaez-dev
#---
#apiVersion: "networking.istio.io/v1alpha3"
#kind: "Gateway"
#metadata:
#  name: "msaez-dev-gateway"
#spec:
#  selector:
#    istio: "ingressgateway"
#  servers:
#    -
#      port:
#        number: 80
#        name: "http"
#        protocol: "HTTP"
#      hosts:
#        - "*"
#---
#  apiVersion: "v1"
#  kind: "Service"
#  metadata:
#    name: msaez-dev
#    labels:
#      app: msaez-dev
#  spec:
#    ports:
#      -
#        port: 80
#        targetPort: 8080
#    selector:
#      app: msaez-dev
#    type: "LoadBalancer"
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: msaez-dev-vsvc
#spec:
#  gateways:
#  - msaez-dev-gateway
#  hosts:
#  - "*"
#  http:
#  - name: primary       # referenced in canary.trafficRouting.istio.virtualService.routes
#    route:
#    - destination:
#        host: msaez-dev
#        subset: stable  # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
#      weight: 100
#    - destination:
#        host: msaez-dev
#        subset: canary  # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
#      weight: 0
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata:
#  name: msaez-dev-destrule
#spec:
#  host: msaez-dev
#  subsets:
#  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
#    labels:        # labels will be injected with canary rollouts-pod-template-hash value
#      app: msaez-dev
#  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
#    labels:        # labels will be injected with canary rollouts-pod-template-hash value
#      app: msaez-dev