FROM sanghoon01/spa-http-server:v1
VOLUME /tmp
#
#RUN npm install -g spa-http-server

ADD dist /opt/www
# ADD .env /opt/www
ADD run.sh /opt/run.sh
ARG VUE_APP_DB_HOST
ENV VUE_APP_DB_HOST=$VUE_APP_DB_HOST
ARG VUE_APP_DB_NAME
ENV VUE_APP_DB_NAME=$VUE_APP_DB_NAME
ARG VUE_APP_DB_PORT
ENV VUE_APP_DB_PORT=$VUE_APP_DB_PORT
ARG VUE_APP_API_HOST
ENV VUE_APP_API_HOST=$VUE_APP_API_HOST
ARG VUE_APP_PROXY_SERVER
ENV VUE_APP_PROXY_SERVER=$VUE_APP_PROXY_SERVER
ARG VUE_APP_GITLAB
ENV VUE_APP_GITLAB=$VUE_APP_GITLAB
ARG VUE_APP_OAUTH_ID
ENV VUE_APP_OAUTH_ID=$VUE_APP_OAUTH_ID
ARG VUE_APP_OAUTH_SECRET
ENV VUE_APP_OAUTH_SECRET=$VUE_APP_OAUTH_SECRET
ARG VUE_APP_OAUTH_URL
ENV VUE_APP_OAUTH_URL=$VUE_APP_OAUTH_URL

EXPOSE 8080
ENTRYPOINT ["sh","/opt/run.sh"]