apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstorming-tool
  labels:
    name: eventstorming-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstorming-tool
  template:
    metadata:
      labels:
        app: eventstorming-tool
    spec:
      containers:
        - name: eventstorming-tool
          env:
            - name: VUE_APP_DB_HOST
              value: {{ .Values.db.host }}
            - name: VUE_APP_DB_PORT
              value: {{ .Values.db.port }}
            - name: VUE_APP_DB_NAME
              value: {{ Values.db.name }}
            - name: VUE_APP_MODE
              value: "onprem"
            - name: VUE_APP_GITLAB
              value: {{ .Values.gitlab.url }}
            - name: VUE_APP_GIT
              value: {{ .Values.provider }}
            - name: VUE_APP_DB_HTTPS
              value: {{ .Values.db.https }}
          image: {{ .Values.image.repository }}/{{ .Values.image.eventstorming }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acebase
  labels:
    name: acebase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acebase
  template:
    metadata:
      labels:
        app: acebase
    spec:
      containers:
        - name: acebase
          image: {{ .Values.image.repository }}/{{ .Values.image.acebase }}
          env:
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_PORT
              value: {{ .Values.db.port }}
            - name: DB_NAME
              value: {{ .Values.db.name }}
            - name: DB_HTTPS
              value: {{ .Values.db.https }}
            - name: CLIENT_ID
              value: {{ .Values.oauth.id }}
            - name: CLIENT_SECRET
              value: {{ .Values.oauth.secret }}
            - name: PROVIDER
              value: {{ .Values.provider }}
            {{- if eq .Values.provider "gitlab" }}  
            - name: GITLAB
              value: {{ .Values.gitlab.url }}
            {{- end }}
          volumeMounts:
          - mountPath: /acebase
            name: acebase
          ports:
            - name: http
              containerPort: 5757
              protocol: TCP
      volumes:
      - name: acebase
        persistentVolumeClaim:
          claimName: acebase-pvc