---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{projectName}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  rules:
    - host: ""
      http:
        paths:
          {{#boundedContexts}}
            {{#aggregates}}
               - path: /{{namePlural}}
                 pathType: Prefix
                 backend:
                   service:
                     name: {{../nameCamelCase}}
                     port:
                       number: 8080
            {{/aggregates}}
          {{/boundedContexts}}

  {{#boundedContexts}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{nameCamelCase}}
  labels:
    app: {{nameCamelCase}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{nameCamelCase}}
  template:
    metadata:
      labels:
        app: {{nameCamelCase}}
    spec:
      containers:
        - name: {{nameCamelCase}}
          image: username/{{nameCamelCase}}:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

  {{/boundedContexts}}
  {{#boundedContexts}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{nameCamelCase}}
  labels:
    app: {{nameCamelCase}}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{nameCamelCase}}

  {{/boundedContexts}}