version: '2'
services:
  axon-server:
    image: axoniq/axonserver
    ports:
      - 8024:8024
      - 8124:8124 
  

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

