server:
  port: 8088

---
spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        {{#boundedContexts}}
         - id: {{name}}
           uri: http://localhost:{{portGenerated}}
           predicates:
            - Path={{#aggregates}}/{{namePlural}}/**{{/aggregates}} {{#views}}/{{namePlural}}/**{{/views}}
        {{/boundedContexts}}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://oauth:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        {{#boundedContexts}}
        - id: {{name}}
          uri: http://{{name}}:8080
          predicates:
            - Path={{#aggregates}}/{{namePlural}}/**{{/aggregates}} {{#views}}/{{namePlural}}/**{{/views}}
        {{/boundedContexts}}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080