server:
  port: 8080
{{#circuitBreaker}}
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 500
{{/circuitBreaker}}
  shutdown: graceful
spring:
  application:
    name: {{toLowerCase name}}
---
spring:
  profiles: default
  datasource:
    hikari:
      maximum-pool-size: 4
    jdbc-url: jdbc:mariadb://localhost:3306/{{options.package}}
    username: USERNAME
    password: PASSWORD

  kafka:
    bootstrap:
      servers: localhost:9092
    consumer:
      properties:
        isolation.level: read_committed
        auto-offset-reset: earliest
        group:
          id: {{name}}
    listener:
      type: batch
      ack-mode: manual

mybatis:
  type-aliases-package: {{options.package}}.dto.entity
  mapper-locations: mapper/xml/*.xml

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: {{portGenerated}}

---
spring:
  profiles: docker
  datasource:
    hikari:
      maximum-pool-size: 4
    jdbc-url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_ID}
    password: ${DB_PWD}

  kafka:
    bootstrap:
      servers: my-kafka.kafka.svc.cluster.local:9092
    consumer:
      properties:
        isolation.level: read_committed
        auto-offset-reset: earliest
        group:
          id: two
    listener:
      type: batch
      ack-mode: manual

mybatis:
  type-aliases-package: {{options.package}}.dto.entity
  mapper-locations: mapper/xml/*.xml

<function>
window.$HandleBars.registerHelper('toLowerCase', function(str) {
  return str.toLowerCase();
});
</function>