replicaCount: 1
image:
  repository: asia-northeast3-docker.pkg.dev/eventstorming-tool/eventstorming # Image Registry
  eventstorming: evenstorming:v49 # Eventstorming-tool Image URL
  acebase: acebase:v33 # Acebase Image URL

provider:
  

gitlab: 
	url: gitlab.handymes.com # Gitlab URL
	oauth: 
		id: # Gitlab Application OAUTH ID
		secret: # Gitlab Application OAUTH Secrets

db:
  host: acebase.handymes.com # DB URL
  port: 443
  name: mydb