name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js 14.21.3
        uses: actions/setup-node@v3
        with:
          node-version: '14.21.3'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        env:
          VUE_APP_FIREBASE_APIKEY: ${{ secrets.VUE_APP_FIREBASE_APIKEY }}
          VUE_APP_FIREBASE_AUTHDOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTHDOMAIN }}
          VUE_APP_FIREBASE_DATABASEURL: ${{ secrets.VUE_APP_FIREBASE_DATABASEURL }}
          VUE_APP_FIREBASE_PROJECTID: ${{ secrets.VUE_APP_FIREBASE_PROJECTID }}
          VUE_APP_FIREBASE_STORAGEBUCKET: ${{ secrets.VUE_APP_FIREBASE_STORAGEBUCKET }}
          VUE_APP_FIREBASE_MESSAGINGSENDERID: ${{ secrets.VUE_APP_FIREBASE_MESSAGINGSENDERID }}
          VUE_APP_FIREBASE_APPID: ${{ secrets.VUE_APP_FIREBASE_APPID }}
          VUE_APP_FIREBASE_MEASUREMENTID: ${{ secrets.VUE_APP_FIREBASE_MEASUREMENTID }}
        run: npm run build

      - name: Install Node.js 18.0.0
        uses: actions/setup-node@v3
        with:
          node-version: '18.0.0'
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVENTSTORMING_TOOL_DB }}
          channelId: live
          projectId: eventstorming-tool-db